spring:
  application:
    name: gateway-service

server:
  port: 80

backend:
  product:
    name: product
    uri: http://localhost:5000
    path:
      inquirylist: /api/product/list
      inquirydetail: /api/product/detail/{id}
  user:
    name: user
    uri: http://localhost:5002
    path:
      login: /api/user/login
      inquirylist: /api/cart/get-cart
      addcart: /api/cart/add-cart


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn

authentication:
  enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
